### ISSUE TITLE
Problema al mostrar el modal

### ISSUE THREAD

**Issue by thereaktorteam** [xavierocampos/Bootstrap-Calendar-PHP-MySQL#1]
Buenas, 

Al hacer clic en el detalle del evento, y desplegarse el modal, debería cargarse la descripción del evento. Sin embargo, el modal aparece en blanco. ¿A que puede ser debido? Adjunto pantallazos del error. 

PD: el código está tal cual viene en el repositorio. La base de datos está generada correctamente y graba bien eventos con todas las columnas correspondientes.

![captura de pantalla 2017-05-03 a la s 13 44 28](https://cloud.githubusercontent.com/assets/26597253/25659139/ab42b5f6-3006-11e7-94a6-dfb4e2e3441c.png)
![captura de pantalla 2017-05-03 a la s 13 44 12](https://cloud.githubusercontent.com/assets/26597253/25659137/ab41ae68-3006-11e7-96f9-6c77f8f34b25.png)
![captura de pantalla 2017-05-03 a la s 13 44 05](https://cloud.githubusercontent.com/assets/26597253/25659138/ab41e8f6-3006-11e7-9b65-255639826ca4.png)

**Comment by jufaba** [comment]
revisa el archivo config.php ahi debes de definir tu dominio o una url local para que en la base de datos de eventos en el campo url quede guardado el url con el id del evento creado

**Comment by xavierocampos** [comment]
Una disculpa por la demora, pero efectivamente tienes que revisar el archivo config.php que es donde se ha de definir el dominio ya que se al momento de registrar el evento, se guarda en la BBDD la url absoluta con el ID para que luego pueda retomarla desde el calendario.

Es un comportamiento sencillo, pero espero les haya sido de ayuda en vuestros proyectos.
