### ISSUE TITLE
No me actualiza cuando cargo evento nuevo

### ISSUE THREAD

**Issue by Agutorres77** [xavierocampos/Bootstrap-Calendar-PHP-MySQL#3]
cuando subo el calendario a una webserver, me carga los eventos en la db pero no me anda la pagina con el "ok", nunca se carga el modal de "evento cargado con exito"

me queda asi la direccion:
/index.php?action=nuevo

nunca me sale con el:
/index.php?nuevo=ok

que puede ser?
gracias

**Comment by xavierocampos** [comment]
Lamentablemente te tengo que decir lo mismo que le dije a otro compañero: No puedo ayudarte, habría que revisar y entender tu proyecto para saber donde está el problema, y eso nadie lo conoce mejor que tu. El calendario fue probado en varios sistemas y nunca dio ningún problema, no obstante es un componente que tiene bastante tiempo sin actualizarse y sería perfectamente normal que arrojase algún fallo por incompatibilidad de cualquier tipo con algún otro componente de tu sistema, pero todo lo que pudiera decir son suposiciones.
